; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -linearize-cfg -linearize-whole-function %s | FileCheck %s

define void @false_br() {
; CHECK-LABEL: @false_br(
; CHECK-NEXT:  dummy.idom:
; CHECK-NEXT:    br label [[ENTRY_GUARD:%.*]]
; CHECK:       entry.guard:
; CHECK-NEXT:    br label [[ENTRY:%.*]]
; CHECK:       entry:
; CHECK-NEXT:    br label [[B1_GUARD:%.*]]
; CHECK:       b1.guard:
; CHECK-NEXT:    br i1 false, label [[B1:%.*]], label [[B2_GUARD:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    br label [[B2_GUARD]]
; CHECK:       b2.guard:
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 2, 2
; CHECK-NEXT:    br i1 [[LAST]], label [[B2:%.*]], label [[B2_SPLIT:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    br label [[B2_SPLIT]]
; CHECK:       b2.split:
; CHECK-NEXT:    ret void
;
entry:
  br i1 false, label %b1, label %b2

b1:
  br label %b2

b2:
  ret void
}

define void @true_br() {
; CHECK-LABEL: @true_br(
; CHECK-NEXT:  dummy.idom:
; CHECK-NEXT:    br label [[ENTRY_GUARD:%.*]]
; CHECK:       entry.guard:
; CHECK-NEXT:    br label [[ENTRY:%.*]]
; CHECK:       entry:
; CHECK-NEXT:    br label [[B1_GUARD:%.*]]
; CHECK:       b1.guard:
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    br label [[B2_GUARD:%.*]]
; CHECK:       b2.guard:
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 2, 2
; CHECK-NEXT:    br i1 [[LAST]], label [[B2:%.*]], label [[B2_SPLIT:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    br label [[B2_SPLIT]]
; CHECK:       b2.split:
; CHECK-NEXT:    ret void
;
entry:
  br i1 true, label %b1, label %b2

b1:
  br label %b2

b2:
  ret void
}

define void @undef_br() {
; CHECK-LABEL: @undef_br(
; CHECK-NEXT:  dummy.idom:
; CHECK-NEXT:    br label [[ENTRY_GUARD:%.*]]
; CHECK:       entry.guard:
; CHECK-NEXT:    br label [[ENTRY:%.*]]
; CHECK:       entry:
; CHECK-NEXT:    br label [[B1_GUARD:%.*]]
; CHECK:       b1.guard:
; CHECK-NEXT:    br i1 false, label [[B1:%.*]], label [[B2_GUARD:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    br label [[B2_GUARD]]
; CHECK:       b2.guard:
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 2, 2
; CHECK-NEXT:    br i1 [[LAST]], label [[B2:%.*]], label [[B2_SPLIT:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    br label [[B2_SPLIT]]
; CHECK:       b2.split:
; CHECK-NEXT:    ret void
;
entry:
  br i1 undef, label %b1, label %b2

b1:
  br label %b2

b2:
  ret void
}
