; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -linearize-cfg %s | FileCheck %s

; unstructured: b3->b6, b2->b5
define void @figure5b(i32 %n) {
; CHECK-LABEL: @figure5b(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC7:%.*]] = phi i32 [ [[I_INC8:%.*]], [[B4_SPLIT:%.*]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_PH:%.*]] = phi i32 [ [[I_INC8]], [[B4_SPLIT]] ], [ 0, [[B1]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_PH]], [[N:%.*]]
; CHECK-NEXT:    [[B2_SUCC_ID:%.*]] = select i1 [[CMP]], i32 5, i32 3
; CHECK-NEXT:    br label [[B3_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[B2_SUCC_ID]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B3:%.*]], label [[B4_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B3_SUCC_ID:%.*]] = select i1 [[COND1]], i32 4, i32 6
; CHECK-NEXT:    br label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[B2_SUCC_ID]], [[B3_GUARD]] ], [ [[B3_SUCC_ID]], [[B3]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR3]], 4
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    store volatile i32 4, i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I_PH]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC8]] = phi i32 [ [[I_INC7]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[GUARD_VAR4:%.*]] = phi i32 [ [[GUARD_VAR3]], [[B4_GUARD]] ], [ 4, [[B4]] ]
; CHECK-NEXT:    [[PREV_GUARD5:%.*]] = icmp eq i32 [[GUARD_VAR4]], 2
; CHECK-NEXT:    br i1 [[PREV_GUARD5]], label [[B2]], label [[B5_GUARD:%.*]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[PREV_GUARD6:%.*]] = icmp eq i32 [[GUARD_VAR4]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD6]], label [[B5:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    store volatile i32 5, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    br label [[B6:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    store volatile i32 6, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %b1

b1:
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b5, label %b3

b3:
  store volatile i32 3, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  store volatile i32 4, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  store volatile i32 5, i32 addrspace(1)* null
  br label %b6

b6:
  store volatile i32 6, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}

define void @figure5b_add_b5_to_b3(i32 %n) {
; CHECK-LABEL: @figure5b_add_b5_to_b3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC8:%.*]] = phi i32 [ [[I_INC9:%.*]], [[B4_SPLIT:%.*]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_PH:%.*]] = phi i32 [ [[I_INC9]], [[B4_SPLIT]] ], [ 0, [[B1]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_PH]], [[N:%.*]]
; CHECK-NEXT:    [[B2_SUCC_ID:%.*]] = select i1 [[CMP]], i32 3, i32 5
; CHECK-NEXT:    br label [[B5_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[B2_SUCC_ID]], [[B5_GUARD]] ], [ [[B5_SUCC_ID:%.*]], [[B5:%.*]] ]
; CHECK-NEXT:    [[PREV_GUARD4:%.*]] = icmp eq i32 [[GUARD_VAR3]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD4]], label [[B3:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B3_SUCC_ID:%.*]] = select i1 [[COND1]], i32 4, i32 6
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR5:%.*]], 4
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    store volatile i32 4, i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I_PH]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC9]] = phi i32 [ [[I_INC8]], [[B4_GUARD:%.*]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 [[GUARD_VAR5]], 2
; CHECK-NEXT:    br i1 [[LAST]], label [[B2]], label [[B6:%.*]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[B2_SUCC_ID]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B5]], label [[B3_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    store volatile i32 5, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND2:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B5_SUCC_ID]] = select i1 [[COND2]], i32 6, i32 3
; CHECK-NEXT:    br label [[B3_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[GUARD_VAR5]] = phi i32 [ [[GUARD_VAR3]], [[B3_GUARD]] ], [ [[B3_SUCC_ID]], [[B3]] ]
; CHECK-NEXT:    [[PREV_GUARD6:%.*]] = icmp eq i32 [[GUARD_VAR5]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD6]], label [[B6]], label [[B4_GUARD]]
; CHECK:       b6:
; CHECK-NEXT:    store volatile i32 6, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %b1

b1:
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b3, label %b5

b3:
  store volatile i32 3, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  store volatile i32 4, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  store volatile i32 5, i32 addrspace(1)* null
  %cond2 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond2, label %b6, label %b3

b6:
  store volatile i32 6, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}

; ; b5 is in a different loop
define void @figure5b_branch_other_loop(i32 %n) {
; CHECK-LABEL: @figure5b_branch_other_loop(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[LOOP2_BODY_SUCC_ID20:%.*]] = phi i32 [ [[LOOP2_BODY_SUCC_ID22:%.*]], [[B4_SPLIT:%.*]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_INC18:%.*]] = phi i32 [ [[I_INC19:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[INNER_LOOP_SUCC_ID15:%.*]] = phi i32 [ [[INNER_LOOP_SUCC_ID17:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_PH:%.*]] = phi i32 [ [[I_INC19]], [[B4_SPLIT]] ], [ 0, [[B1]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_PH]], [[N:%.*]]
; CHECK-NEXT:    [[B2_SUCC_ID:%.*]] = select i1 [[CMP]], i32 3, i32 6
; CHECK-NEXT:    br label [[B5_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD6:%.*]] = icmp eq i32 [[GUARD_VAR4:%.*]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD6]], label [[B3:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B3_SUCC_ID:%.*]] = select i1 [[COND1]], i32 4, i32 8
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       inner.loop.guard:
; CHECK-NEXT:    [[INNER_LOOP_SUCC_ID16:%.*]] = phi i32 [ [[INNER_LOOP_SUCC_ID15]], [[B6_GUARD]] ], [ [[INNER_LOOP_SUCC_ID17]], [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE:%.*]] ]
; CHECK-NEXT:    [[GUARD_VAR9:%.*]] = phi i32 [ [[GUARD_VAR7:%.*]], [[B6_GUARD]] ], [ [[INNER_LOOP_SUCC_ID17]], [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE]] ]
; CHECK-NEXT:    [[BE_GUARD10:%.*]] = icmp eq i32 [[GUARD_VAR9]], 4
; CHECK-NEXT:    br i1 [[BE_GUARD10]], label [[INNER_LOOP:%.*]], label [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE]]
; CHECK:       inner.loop:
; CHECK-NEXT:    [[INNER_COND:%.*]] = load i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[INNER_LOOP_SUCC_ID:%.*]] = select i1 [[INNER_COND]], i32 4, i32 5
; CHECK-NEXT:    br label [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE]]
; CHECK:       inner.loop.inner.loop.guard_crit_edge:
; CHECK-NEXT:    [[INNER_LOOP_SUCC_ID17]] = phi i32 [ [[INNER_LOOP_SUCC_ID16]], [[INNER_LOOP_GUARD:%.*]] ], [ [[INNER_LOOP_SUCC_ID]], [[INNER_LOOP]] ]
; CHECK-NEXT:    [[GUARD_VAR11:%.*]] = phi i32 [ [[GUARD_VAR9]], [[INNER_LOOP_GUARD]] ], [ [[INNER_LOOP_SUCC_ID]], [[INNER_LOOP]] ]
; CHECK-NEXT:    [[PREV_GUARD12:%.*]] = icmp eq i32 [[GUARD_VAR11]], 4
; CHECK-NEXT:    br i1 [[PREV_GUARD12]], label [[INNER_LOOP_GUARD]], label [[B4_GUARD:%.*]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[BE_GUARD14:%.*]] = icmp eq i32 [[GUARD_VAR11]], 5
; CHECK-NEXT:    br i1 [[BE_GUARD14]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    store volatile i32 4, i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I_PH]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC19]] = phi i32 [ [[I_INC18]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 [[GUARD_VAR11]], 2
; CHECK-NEXT:    br i1 [[LAST]], label [[B2]], label [[B6:%.*]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[LOOP2_BODY_SUCC_ID21:%.*]] = phi i32 [ [[LOOP2_BODY_SUCC_ID22]], [[LOOP2_BODY_B5_GUARD_CRIT_EDGE:%.*]] ], [ [[LOOP2_BODY_SUCC_ID20]], [[B2]] ]
; CHECK-NEXT:    [[GUARD_VAR1:%.*]] = phi i32 [ [[LOOP2_BODY_SUCC_ID22]], [[LOOP2_BODY_B5_GUARD_CRIT_EDGE]] ], [ [[B2_SUCC_ID]], [[B2]] ]
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[GUARD_VAR1]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B5:%.*]], label [[LOOP2_BODY_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    store volatile i32 5, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND2:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B5_SUCC_ID:%.*]] = select i1 [[COND2]], i32 7, i32 8
; CHECK-NEXT:    br label [[LOOP2_BODY_GUARD]]
; CHECK:       loop2.body.guard:
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[GUARD_VAR1]], [[B5_GUARD]] ], [ [[B5_SUCC_ID]], [[B5]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR3]], 7
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[LOOP2_BODY:%.*]], label [[LOOP2_BODY_B5_GUARD_CRIT_EDGE]]
; CHECK:       loop2.body:
; CHECK-NEXT:    [[COND3:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[LOOP2_BODY_SUCC_ID:%.*]] = select i1 [[COND3]], i32 7, i32 8
; CHECK-NEXT:    br label [[LOOP2_BODY_B5_GUARD_CRIT_EDGE]]
; CHECK:       loop2.body.b5.guard_crit_edge:
; CHECK-NEXT:    [[LOOP2_BODY_SUCC_ID22]] = phi i32 [ [[LOOP2_BODY_SUCC_ID21]], [[LOOP2_BODY_GUARD]] ], [ [[LOOP2_BODY_SUCC_ID]], [[LOOP2_BODY]] ]
; CHECK-NEXT:    [[GUARD_VAR4]] = phi i32 [ [[GUARD_VAR3]], [[LOOP2_BODY_GUARD]] ], [ [[LOOP2_BODY_SUCC_ID]], [[LOOP2_BODY]] ]
; CHECK-NEXT:    [[PREV_GUARD5:%.*]] = icmp eq i32 [[GUARD_VAR4]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD5]], label [[B5_GUARD]], label [[B3_GUARD:%.*]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[GUARD_VAR7]] = phi i32 [ [[GUARD_VAR4]], [[B3_GUARD]] ], [ [[B3_SUCC_ID]], [[B3]] ]
; CHECK-NEXT:    [[PREV_GUARD8:%.*]] = icmp eq i32 [[GUARD_VAR7]], 8
; CHECK-NEXT:    br i1 [[PREV_GUARD8]], label [[B6]], label [[INNER_LOOP_GUARD]]
; CHECK:       b6:
; CHECK-NEXT:    store volatile i32 6, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %b1

b1:
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b3, label %b5

b3:
  store volatile i32 3, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %inner.loop, label %b6

inner.loop:
  %inner.cond = load i1, i1 addrspace(1)* null
  br i1 %inner.cond, label %inner.loop, label %b4

b4:
  store volatile i32 4, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  store volatile i32 5, i32 addrspace(1)* null
  %cond2 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond2, label %loop2.body, label %b6

loop2.body:
  %cond3 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond3, label %b5, label %b6

b6:
  store volatile i32 6, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}

define void @figure5b_phis(i32 %n) {
; CHECK-LABEL: @figure5b_phis(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ENTRY_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_PHI:%.*]] = phi i32 [ [[ENTRY_LOAD]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    store volatile i32 [[B1_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC11:%.*]] = phi i32 [ [[I_INC12:%.*]], [[B4_SPLIT:%.*]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B4_LOAD9:%.*]] = phi i32 [ [[B4_LOAD10:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B6_PHI_PH7:%.*]] = phi i32 [ [[B6_PHI_PH8:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_PH:%.*]] = phi i32 [ [[I_INC12]], [[B4_SPLIT]] ], [ 0, [[B1]] ]
; CHECK-NEXT:    [[B2_PHI_PH:%.*]] = phi i32 [ [[B4_LOAD10]], [[B4_SPLIT]] ], [ [[B1_LOAD]], [[B1]] ]
; CHECK-NEXT:    store volatile i32 [[B2_PHI_PH]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B2_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_PH]], [[N:%.*]]
; CHECK-NEXT:    [[B2_SUCC_ID:%.*]] = select i1 [[CMP]], i32 5, i32 3
; CHECK-NEXT:    br label [[B3_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[B2_SUCC_ID]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B3:%.*]], label [[B4_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    [[B3_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B3_GUARD]] ]
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[B3_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B3_SUCC_ID:%.*]] = select i1 [[COND1]], i32 4, i32 6
; CHECK-NEXT:    br label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[B6_PHI_PH8]] = phi i32 [ [[B6_PHI_PH7]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[B2_SUCC_ID]], [[B3_GUARD]] ], [ [[B3_SUCC_ID]], [[B3]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR3]], 4
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    [[B4_PHI:%.*]] = phi i32 [ [[B6_PHI_PH8]], [[B4_GUARD]] ]
; CHECK-NEXT:    [[B4_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B4_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I_PH]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC12]] = phi i32 [ [[I_INC11]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[B4_LOAD10]] = phi i32 [ [[B4_LOAD9]], [[B4_GUARD]] ], [ [[B4_LOAD]], [[B4]] ]
; CHECK-NEXT:    [[GUARD_VAR4:%.*]] = phi i32 [ [[GUARD_VAR3]], [[B4_GUARD]] ], [ 4, [[B4]] ]
; CHECK-NEXT:    [[PREV_GUARD5:%.*]] = icmp eq i32 [[GUARD_VAR4]], 2
; CHECK-NEXT:    br i1 [[PREV_GUARD5]], label [[B2]], label [[B5_GUARD:%.*]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[PREV_GUARD6:%.*]] = icmp eq i32 [[GUARD_VAR4]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD6]], label [[B5:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    [[B5_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[B5_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B5_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[B6_PHI_PH:%.*]] = phi i32 [ [[B5_LOAD]], [[B5]] ], [ [[B6_PHI_PH8]], [[B5_GUARD]] ]
; CHECK-NEXT:    br label [[B6:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    [[B6_PHI:%.*]] = phi i32 [ [[B6_PHI_PH]], [[B6_GUARD]] ]
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %entry.load = load volatile i32, i32 addrspace(1)* null
  br label %b1

b1:
  %b1.phi = phi i32 [ %entry.load, %entry ]
  store volatile i32 %b1.phi, i32 addrspace(1)* null
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %b2.phi = phi i32 [ %b1.load, %b1 ], [ %b4.load, %b4 ]
  store volatile i32 %b2.phi, i32 addrspace(1)* null
  %b2.load = load volatile i32, i32 addrspace(1)* null
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b5, label %b3

b3:
  %b3.phi = phi i32 [ %b2.load, %b2 ]
  store volatile i32 3, i32 addrspace(1)* null
  %b3.load = load volatile i32, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  %b4.phi = phi i32 [ %b3.load, %b3 ]
  %b4.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b4.phi, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  %b5.phi = phi i32 [ %b2.load, %b2 ]
  %b5.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b5.phi, i32 addrspace(1)* null
  br label %b6

b6:
  %b6.phi = phi i32 [ %b3.load, %b3 ], [ %b5.load, %b5 ]
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}









; swap order of branch in b2
define void @figure5b_phis_swap_br2(i32 %n) {
; CHECK-LABEL: @figure5b_phis_swap_br2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ENTRY_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_PHI:%.*]] = phi i32 [ [[ENTRY_LOAD]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    store volatile i32 [[B1_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[B5_LOAD17:%.*]] = phi i32 [ [[B5_LOAD18:%.*]], [[B4_SPLIT:%.*]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_INC15:%.*]] = phi i32 [ [[I_INC16:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B4_LOAD13:%.*]] = phi i32 [ [[B4_LOAD14:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B3_LOAD11:%.*]] = phi i32 [ [[B3_LOAD12:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B6_PHI9:%.*]] = phi i32 [ [[B6_PHI_PH:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B6_PHI_PH5:%.*]] = phi i32 [ [[B3_LOAD12]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_PH:%.*]] = phi i32 [ [[I_INC16]], [[B4_SPLIT]] ], [ 0, [[B1]] ]
; CHECK-NEXT:    [[B2_PHI_PH:%.*]] = phi i32 [ [[B4_LOAD14]], [[B4_SPLIT]] ], [ [[B1_LOAD]], [[B1]] ]
; CHECK-NEXT:    store volatile i32 [[B2_PHI_PH]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B2_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_PH]], [[N:%.*]]
; CHECK-NEXT:    [[B2_SUCC_ID:%.*]] = select i1 [[CMP]], i32 3, i32 5
; CHECK-NEXT:    br label [[B5_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[B5_LOAD18]] = phi i32 [ [[B5_LOAD:%.*]], [[B5:%.*]] ], [ [[B5_LOAD17]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ 6, [[B5]] ], [ [[B2_SUCC_ID]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[PREV_GUARD4:%.*]] = icmp eq i32 [[GUARD_VAR3]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD4]], label [[B3:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    [[B3_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B3_GUARD:%.*]] ]
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[B3_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B3_SUCC_ID:%.*]] = select i1 [[COND1]], i32 4, i32 6
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR6:%.*]], 4
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    [[B4_PHI:%.*]] = phi i32 [ [[B3_LOAD12]], [[B4_GUARD:%.*]] ]
; CHECK-NEXT:    [[B4_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B4_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I_PH]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC16]] = phi i32 [ [[I_INC15]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[B4_LOAD14]] = phi i32 [ [[B4_LOAD13]], [[B4_GUARD]] ], [ [[B4_LOAD]], [[B4]] ]
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 [[GUARD_VAR6]], 2
; CHECK-NEXT:    br i1 [[LAST]], label [[B2]], label [[B6:%.*]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[B2_SUCC_ID]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B5]], label [[B3_GUARD]]
; CHECK:       b5:
; CHECK-NEXT:    [[B5_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[B5_LOAD]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B5_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B3_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[B3_LOAD12]] = phi i32 [ [[B3_LOAD11]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[GUARD_VAR6]] = phi i32 [ [[GUARD_VAR3]], [[B3_GUARD]] ], [ [[B3_SUCC_ID]], [[B3]] ]
; CHECK-NEXT:    [[B6_PHI_PH]] = phi i32 [ [[B5_LOAD18]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[PREV_GUARD7:%.*]] = icmp eq i32 [[GUARD_VAR6]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD7]], label [[B6]], label [[B4_GUARD]]
; CHECK:       b6:
; CHECK-NEXT:    [[B6_PHI:%.*]] = phi i32 [ [[B6_PHI_PH]], [[B6_GUARD]] ], [ [[B6_PHI_PH]], [[B4_SPLIT]] ]
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %entry.load = load volatile i32, i32 addrspace(1)* null
  br label %b1

b1:
  %b1.phi = phi i32 [ %entry.load, %entry ]
  store volatile i32 %b1.phi, i32 addrspace(1)* null
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %b2.phi = phi i32 [ %b1.load, %b1 ], [ %b4.load, %b4 ]
  store volatile i32 %b2.phi, i32 addrspace(1)* null
  %b2.load = load volatile i32, i32 addrspace(1)* null
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b3, label %b5

b3:
  %b3.phi = phi i32 [ %b2.load, %b2 ]
  store volatile i32 3, i32 addrspace(1)* null
  %b3.load = load volatile i32, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  %b4.phi = phi i32 [ %b3.load, %b3 ]
  %b4.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b4.phi, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  %b5.phi = phi i32 [ %b2.load, %b2 ]
  %b5.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b5.phi, i32 addrspace(1)* null
  br label %b6

b6:
  %b6.phi = phi i32 [ %b3.load, %b3 ], [ %b5.load, %b5 ]
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}

; structured condition skips over unstructured region.
define void @guarded_figure5b_phis(i1 %cond0, i32 %n) {
; CHECK-LABEL: @guarded_figure5b_phis(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ENTRY_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 100, i32 addrspace(1)* null
; CHECK-NEXT:    br i1 [[COND0:%.*]], label [[B0:%.*]], label [[EXIT:%.*]]
; CHECK:       b0:
; CHECK-NEXT:    [[B0_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_PHI:%.*]] = phi i32 [ [[B0_LOAD]], [[B0]] ]
; CHECK-NEXT:    store volatile i32 [[B1_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC11:%.*]] = phi i32 [ [[I_INC12:%.*]], [[B4_SPLIT:%.*]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B4_LOAD9:%.*]] = phi i32 [ [[B4_LOAD10:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B6_PHI_PH7:%.*]] = phi i32 [ [[B6_PHI_PH8:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_PH:%.*]] = phi i32 [ [[I_INC12]], [[B4_SPLIT]] ], [ 0, [[B1]] ]
; CHECK-NEXT:    [[B2_PHI_PH:%.*]] = phi i32 [ [[B4_LOAD10]], [[B4_SPLIT]] ], [ [[B1_LOAD]], [[B1]] ]
; CHECK-NEXT:    store volatile i32 [[B2_PHI_PH]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B2_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_PH]], [[N:%.*]]
; CHECK-NEXT:    [[B2_SUCC_ID:%.*]] = select i1 [[CMP]], i32 6, i32 4
; CHECK-NEXT:    br label [[B3_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[B2_SUCC_ID]], 4
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B3:%.*]], label [[B4_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    [[B3_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B3_GUARD]] ]
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[B3_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B3_SUCC_ID:%.*]] = select i1 [[COND1]], i32 5, i32 7
; CHECK-NEXT:    br label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[B6_PHI_PH8]] = phi i32 [ [[B6_PHI_PH7]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[B2_SUCC_ID]], [[B3_GUARD]] ], [ [[B3_SUCC_ID]], [[B3]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR3]], 5
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    [[B4_PHI:%.*]] = phi i32 [ [[B6_PHI_PH8]], [[B4_GUARD]] ]
; CHECK-NEXT:    [[B4_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B4_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I_PH]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC12]] = phi i32 [ [[I_INC11]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[B4_LOAD10]] = phi i32 [ [[B4_LOAD9]], [[B4_GUARD]] ], [ [[B4_LOAD]], [[B4]] ]
; CHECK-NEXT:    [[GUARD_VAR4:%.*]] = phi i32 [ [[GUARD_VAR3]], [[B4_GUARD]] ], [ 5, [[B4]] ]
; CHECK-NEXT:    [[PREV_GUARD5:%.*]] = icmp eq i32 [[GUARD_VAR4]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD5]], label [[B2]], label [[B5_GUARD:%.*]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[PREV_GUARD6:%.*]] = icmp eq i32 [[GUARD_VAR4]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD6]], label [[B5:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    [[B5_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[B5_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B5_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[B6_PHI_PH:%.*]] = phi i32 [ [[B5_LOAD]], [[B5]] ], [ [[B6_PHI_PH8]], [[B5_GUARD]] ]
; CHECK-NEXT:    br label [[B6:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    [[B6_PHI:%.*]] = phi i32 [ [[B6_PHI_PH]], [[B6_GUARD]] ]
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[EXIT_PHI:%.*]] = phi i32 [ [[B6_PHI]], [[B6]] ], [ [[ENTRY_LOAD]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    store volatile i32 [[EXIT_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    ret void
;
entry:
  %entry.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 100, i32 addrspace(1)* null
  br i1 %cond0, label %b0, label %exit

b0:
  %b0.load = load volatile i32, i32 addrspace(1)* null
  br label %b1

b1:
  %b1.phi = phi i32 [ %b0.load, %b0 ]
  store volatile i32 %b1.phi, i32 addrspace(1)* null
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %b2.phi = phi i32 [ %b1.load, %b1 ], [ %b4.load, %b4 ]
  store volatile i32 %b2.phi, i32 addrspace(1)* null
  %b2.load = load volatile i32, i32 addrspace(1)* null
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b5, label %b3

b3:
  %b3.phi = phi i32 [ %b2.load, %b2 ]
  store volatile i32 3, i32 addrspace(1)* null
  %b3.load = load volatile i32, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  %b4.phi = phi i32 [ %b3.load, %b3 ]
  %b4.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b4.phi, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  %b5.phi = phi i32 [ %b2.load, %b2 ]
  %b5.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b5.phi, i32 addrspace(1)* null
  br label %b6

b6:
  %b6.phi = phi i32 [ %b3.load, %b3 ], [ %b5.load, %b5 ]
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  br label %exit

exit:
  %exit.phi = phi i32 [ %b6.phi, %b6 ], [ %entry.load, %entry ]
  store volatile i32 %exit.phi, i32 addrspace(1)* null
  ret void
}

; The block before the unstructured region has 2 predecessors
define void @multiple_entry_unstructured_region_figure5b_phis(i1 %cond0, i32 %n) {
; CHECK-LABEL: @multiple_entry_unstructured_region_figure5b_phis(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ENTRY_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 100, i32 addrspace(1)* null
; CHECK-NEXT:    br i1 [[COND0:%.*]], label [[PRE_0:%.*]], label [[PRE_1:%.*]]
; CHECK:       pre.0:
; CHECK-NEXT:    [[PRE_0_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 123, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       pre.1:
; CHECK-NEXT:    [[PRE_1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 123, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_PHI:%.*]] = phi i32 [ [[PRE_0_LOAD]], [[PRE_0]] ], [ [[PRE_1_LOAD]], [[PRE_1]] ]
; CHECK-NEXT:    store volatile i32 [[B1_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC11:%.*]] = phi i32 [ [[I_INC12:%.*]], [[B4_SPLIT:%.*]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B4_LOAD9:%.*]] = phi i32 [ [[B4_LOAD10:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[B6_PHI_PH7:%.*]] = phi i32 [ [[B6_PHI_PH8:%.*]], [[B4_SPLIT]] ], [ undef, [[B1]] ]
; CHECK-NEXT:    [[I_PH:%.*]] = phi i32 [ [[I_INC12]], [[B4_SPLIT]] ], [ 0, [[B1]] ]
; CHECK-NEXT:    [[B2_PHI_PH:%.*]] = phi i32 [ [[B4_LOAD10]], [[B4_SPLIT]] ], [ [[B1_LOAD]], [[B1]] ]
; CHECK-NEXT:    store volatile i32 [[B2_PHI_PH]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B2_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_PH]], [[N:%.*]]
; CHECK-NEXT:    [[B2_SUCC_ID:%.*]] = select i1 [[CMP]], i32 7, i32 5
; CHECK-NEXT:    br label [[B3_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[B2_SUCC_ID]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B3:%.*]], label [[B4_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    [[B3_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B3_GUARD]] ]
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[B3_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[B3_SUCC_ID:%.*]] = select i1 [[COND1]], i32 6, i32 8
; CHECK-NEXT:    br label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[B6_PHI_PH8]] = phi i32 [ [[B6_PHI_PH7]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[B2_SUCC_ID]], [[B3_GUARD]] ], [ [[B3_SUCC_ID]], [[B3]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR3]], 6
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    [[B4_PHI:%.*]] = phi i32 [ [[B6_PHI_PH8]], [[B4_GUARD]] ]
; CHECK-NEXT:    [[B4_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B4_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I_PH]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC12]] = phi i32 [ [[I_INC11]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[B4_LOAD10]] = phi i32 [ [[B4_LOAD9]], [[B4_GUARD]] ], [ [[B4_LOAD]], [[B4]] ]
; CHECK-NEXT:    [[GUARD_VAR4:%.*]] = phi i32 [ [[GUARD_VAR3]], [[B4_GUARD]] ], [ 6, [[B4]] ]
; CHECK-NEXT:    [[PREV_GUARD5:%.*]] = icmp eq i32 [[GUARD_VAR4]], 4
; CHECK-NEXT:    br i1 [[PREV_GUARD5]], label [[B2]], label [[B5_GUARD:%.*]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[PREV_GUARD6:%.*]] = icmp eq i32 [[GUARD_VAR4]], 7
; CHECK-NEXT:    br i1 [[PREV_GUARD6]], label [[B5:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    [[B5_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[B5_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B5_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[B6_PHI_PH:%.*]] = phi i32 [ [[B5_LOAD]], [[B5]] ], [ [[B6_PHI_PH8]], [[B5_GUARD]] ]
; CHECK-NEXT:    br label [[B6:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    [[B6_PHI:%.*]] = phi i32 [ [[B6_PHI_PH]], [[B6_GUARD]] ]
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    ret void
;
entry:
  %entry.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 100, i32 addrspace(1)* null
  br i1 %cond0, label %pre.0, label %pre.1

pre.0:
  %pre.0.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 123, i32 addrspace(1)* null
  br label %b1

pre.1:
  %pre.1.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 123, i32 addrspace(1)* null
  br label %b1

b1:
  %b1.phi = phi i32 [ %pre.0.load, %pre.0 ], [ %pre.1.load, %pre.1 ]
  store volatile i32 %b1.phi, i32 addrspace(1)* null
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %b2.phi = phi i32 [ %b1.load, %b1 ], [ %b4.load, %b4 ]
  store volatile i32 %b2.phi, i32 addrspace(1)* null
  %b2.load = load volatile i32, i32 addrspace(1)* null
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b5, label %b3

b3:
  %b3.phi = phi i32 [ %b2.load, %b2 ]
  store volatile i32 3, i32 addrspace(1)* null
  %b3.load = load volatile i32, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  %b4.phi = phi i32 [ %b3.load, %b3 ]
  %b4.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b4.phi, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  %b5.phi = phi i32 [ %b2.load, %b2 ]
  %b5.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b5.phi, i32 addrspace(1)* null
  br label %b6

b6:
  %b6.phi = phi i32 [ %b3.load, %b3 ], [ %b5.load, %b5 ]
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  br label %exit

exit:
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  ret void
}
