; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -linearize-cfg %s | FileCheck %s

define void @figure6c(i1 %cond0, i1 %cond1, i1 %cond2) {
; CHECK-LABEL: @figure6c(
; CHECK-NEXT:  b1:
; CHECK-NEXT:    store volatile i32 1, i32 addrspace(1)* null
; CHECK-NEXT:    br i1 [[COND0:%.*]], label [[B2_GUARD:%.*]], label [[B3_GUARD:%.*]]
; CHECK:       b2.guard:
; CHECK-NEXT:    [[GUARD_VAR:%.*]] = phi i32 [ 1, [[B1:%.*]] ], [ 2, [[B3_SPLIT:%.*]] ]
; CHECK-NEXT:    [[PREV_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR]], 1
; CHECK-NEXT:    br i1 [[PREV_GUARD]], label [[B2:%.*]], label [[B3_GUARD]]
; CHECK:       b2:
; CHECK-NEXT:    store volatile i32 2, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B3_GUARD]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[GUARD_VAR1:%.*]] = phi i32 [ [[GUARD_VAR]], [[B2_GUARD]] ], [ 1, [[B1]] ], [ 2, [[B2]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR1]], 2
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B3:%.*]], label [[B3_SPLIT]]
; CHECK:       b3:
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B3_SPLIT]]
; CHECK:       b3.split:
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 [[GUARD_VAR1]], 1
; CHECK-NEXT:    br i1 [[LAST]], label [[B2_GUARD]], label [[B3]]
;
b1:
  store volatile i32 1, i32 addrspace(1)* null
  br i1 %cond0, label %b2, label %b3

b2:
  store volatile i32 2, i32 addrspace(1)* null
  br label %b3

b3:
  store volatile i32 3, i32 addrspace(1)* null
  br label %b2
}
