; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -linearize-cfg %s | FileCheck %s

; Unstructured blocks: b2, b3, b4, b5, b6

define void @figure8a() {
; CHECK-LABEL: @figure8a(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    store volatile i32 1, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    store volatile i32 2, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND0:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    br i1 [[COND0]], label [[EXIT:%.*]], label [[B3:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B4:%.*]]
; CHECK:       b4:
; CHECK-NEXT:    store volatile i32 4, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    br i1 [[COND1]], label [[B6:%.*]], label [[B5:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    store volatile i32 5, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B4]]
; CHECK:       b6:
; CHECK-NEXT:    store volatile i32 6, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2]]
; CHECK:       exit:
; CHECK-NEXT:    store volatile i32 7, i32 addrspace(1)* null
; CHECK-NEXT:    ret void
;
entry:
  br label %b1

b1:
  store volatile i32 1, i32 addrspace(1)* null
  br label %b2

b2:
  store volatile i32 2, i32 addrspace(1)* null
  %cond0 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond0, label %exit, label %b3

b3:
  store volatile i32 3, i32 addrspace(1)* null
  br label %b4

b4:
  store volatile i32 4, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b6, label %b5

b5:
  store volatile i32 5, i32 addrspace(1)* null
  br label %b4

b6:
  store volatile i32 6, i32 addrspace(1)* null
  br label %b2

exit:
  store volatile i32 7, i32 addrspace(1)* null
  ret void
}
