; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -linearize-cfg %s | FileCheck %s

; unstructured: b3->b6, b2->b5
define void @figure5b(i32 %n) {
; CHECK-LABEL: @figure5b(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC5:%.*]] = phi i32 [ undef, [[B1]] ], [ [[I_INC6:%.*]], [[B4_SPLIT:%.*]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[B1]] ], [ [[I_INC6]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N:%.*]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[CMP]], i32 5, i32 3
; CHECK-NEXT:    br i1 [[CMP]], label [[B5_GUARD:%.*]], label [[B3_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD:%.*]] = icmp eq i32 [[TMP0]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD]], label [[B3:%.*]], label [[B4_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND1]], i32 4, i32 6
; CHECK-NEXT:    br label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[GUARD_VAR:%.*]] = phi i32 [ [[TMP0]], [[B3_GUARD]] ], [ [[TMP1]], [[B3]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR]], 4
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    store volatile i32 4, i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC6]] = phi i32 [ [[I_INC5]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[GUARD_VAR1:%.*]] = phi i32 [ [[GUARD_VAR]], [[B4_GUARD]] ], [ 4, [[B4]] ]
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[GUARD_VAR1]], 2
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B2]], label [[B5_GUARD]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[GUARD_VAR1]], [[B4_SPLIT]] ], [ [[TMP0]], [[B2]] ]
; CHECK-NEXT:    [[PREV_GUARD4:%.*]] = icmp eq i32 [[GUARD_VAR3]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD4]], label [[B5:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    store volatile i32 5, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    br label [[B6:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    store volatile i32 6, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %b1

b1:
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b5, label %b3

b3:
  store volatile i32 3, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  store volatile i32 4, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  store volatile i32 5, i32 addrspace(1)* null
  br label %b6

b6:
  store volatile i32 6, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}

define void @figure5b_add_b5_to_b3(i32 %n) {
; CHECK-LABEL: @figure5b_add_b5_to_b3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[B1]] ], [ [[I_INC:%.*]], [[B4_SPLIT:%.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N:%.*]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[CMP]], i32 3, i32 5
; CHECK-NEXT:    br label [[B5_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[GUARD_VAR:%.*]] = phi i32 [ [[TMP0]], [[B5_GUARD]] ], [ [[TMP2:%.*]], [[B5:%.*]] ]
; CHECK-NEXT:    [[PREV_GUARD1:%.*]] = icmp eq i32 [[GUARD_VAR]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD1]], label [[B3:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND1]], i32 4, i32 6
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 [[GUARD_VAR2:%.*]], 4
; CHECK-NEXT:    br i1 [[LAST]], label [[B4:%.*]], label [[B6:%.*]]
; CHECK:       b4:
; CHECK-NEXT:    store volatile i32 4, i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC]] = add nsw i32 [[I]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    br label [[B2]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[PREV_GUARD:%.*]] = icmp eq i32 [[TMP0]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD]], label [[B5]], label [[B3_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    store volatile i32 5, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND2:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP2]] = select i1 [[COND2]], i32 6, i32 3
; CHECK-NEXT:    br label [[B3_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[GUARD_VAR2]] = phi i32 [ [[GUARD_VAR]], [[B3_GUARD]] ], [ [[TMP1]], [[B3]] ]
; CHECK-NEXT:    [[PREV_GUARD3:%.*]] = icmp eq i32 [[GUARD_VAR2]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD3]], label [[B6]], label [[B4_GUARD:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    store volatile i32 6, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %b1

b1:
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b3, label %b5

b3:
  store volatile i32 3, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  store volatile i32 4, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  store volatile i32 5, i32 addrspace(1)* null
  %cond2 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond2, label %b6, label %b3

b6:
  store volatile i32 6, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}

; ; b5 is in a different loop
define void @figure5b_branch_other_loop(i32 %n) {
; CHECK-LABEL: @figure5b_branch_other_loop(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i32 [ undef, [[B1]] ], [ [[TMP3:%.*]], [[B4_SPLIT:%.*]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = phi i32 [ undef, [[B1]] ], [ [[TMP8:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[B1]] ], [ [[I_INC:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[CMP]], i32 3, i32 6
; CHECK-NEXT:    br i1 [[CMP]], label [[B3_GUARD:%.*]], label [[B5_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[TMP3]] = phi i32 [ [[TMP12:%.*]], [[LOOP2_BODY_B5_GUARD_CRIT_EDGE:%.*]] ], [ [[TMP0]], [[B2]] ]
; CHECK-NEXT:    [[GUARD_VAR4:%.*]] = phi i32 [ [[GUARD_VAR2:%.*]], [[LOOP2_BODY_B5_GUARD_CRIT_EDGE]] ], [ [[TMP2]], [[B2]] ]
; CHECK-NEXT:    [[PREV_GUARD5:%.*]] = icmp eq i32 [[GUARD_VAR4]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD5]], label [[B3:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP4:%.*]] = select i1 [[COND1]], i32 4, i32 8
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       inner.loop.guard:
; CHECK-NEXT:    [[TMP5:%.*]] = phi i32 [ [[TMP1]], [[B6_GUARD]] ], [ [[TMP7:%.*]], [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE:%.*]] ]
; CHECK-NEXT:    [[GUARD_VAR8:%.*]] = phi i32 [ [[GUARD_VAR6:%.*]], [[B6_GUARD]] ], [ [[TMP7]], [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE]] ]
; CHECK-NEXT:    [[BE_GUARD9:%.*]] = icmp eq i32 [[GUARD_VAR8]], 4
; CHECK-NEXT:    br i1 [[BE_GUARD9]], label [[INNER_LOOP:%.*]], label [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE]]
; CHECK:       inner.loop:
; CHECK-NEXT:    [[INNER_COND:%.*]] = load i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP6:%.*]] = select i1 [[INNER_COND]], i32 4, i32 5
; CHECK-NEXT:    br i1 [[INNER_COND]], label [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE]], label [[B4_GUARD:%.*]]
; CHECK:       inner.loop.inner.loop.guard_crit_edge:
; CHECK-NEXT:    [[TMP7]] = phi i32 [ [[TMP5]], [[INNER_LOOP_GUARD:%.*]] ], [ [[TMP6]], [[INNER_LOOP]] ]
; CHECK-NEXT:    [[GUARD_VAR10:%.*]] = phi i32 [ [[GUARD_VAR8]], [[INNER_LOOP_GUARD]] ], [ [[TMP6]], [[INNER_LOOP]] ]
; CHECK-NEXT:    [[PREV_GUARD11:%.*]] = icmp eq i32 [[GUARD_VAR10]], 4
; CHECK-NEXT:    br i1 [[PREV_GUARD11]], label [[INNER_LOOP_GUARD]], label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[TMP8]] = phi i32 [ [[TMP7]], [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE]] ], [ [[TMP6]], [[INNER_LOOP]] ]
; CHECK-NEXT:    [[GUARD_VAR12:%.*]] = phi i32 [ [[GUARD_VAR10]], [[INNER_LOOP_INNER_LOOP_GUARD_CRIT_EDGE]] ], [ [[TMP6]], [[INNER_LOOP]] ]
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 [[GUARD_VAR12]], 5
; CHECK-NEXT:    br i1 [[LAST]], label [[B4:%.*]], label [[B6:%.*]]
; CHECK:       b4:
; CHECK-NEXT:    store volatile i32 4, i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC]] = add nsw i32 [[I]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    br label [[B2]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[TMP9:%.*]] = phi i32 [ [[TMP12]], [[LOOP2_BODY_B5_GUARD_CRIT_EDGE]] ], [ [[TMP0]], [[B2]] ]
; CHECK-NEXT:    [[GUARD_VAR:%.*]] = phi i32 [ [[TMP12]], [[LOOP2_BODY_B5_GUARD_CRIT_EDGE]] ], [ [[TMP2]], [[B2]] ]
; CHECK-NEXT:    [[PREV_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD]], label [[B5:%.*]], label [[LOOP2_BODY_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    store volatile i32 5, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND2:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP10:%.*]] = select i1 [[COND2]], i32 7, i32 8
; CHECK-NEXT:    br label [[LOOP2_BODY_GUARD]]
; CHECK:       loop2.body.guard:
; CHECK-NEXT:    [[GUARD_VAR1:%.*]] = phi i32 [ [[GUARD_VAR]], [[B5_GUARD]] ], [ [[TMP10]], [[B5]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR1]], 7
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[LOOP2_BODY:%.*]], label [[LOOP2_BODY_B5_GUARD_CRIT_EDGE]]
; CHECK:       loop2.body:
; CHECK-NEXT:    [[COND3:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP11:%.*]] = select i1 [[COND3]], i32 7, i32 8
; CHECK-NEXT:    br label [[LOOP2_BODY_B5_GUARD_CRIT_EDGE]]
; CHECK:       loop2.body.b5.guard_crit_edge:
; CHECK-NEXT:    [[TMP12]] = phi i32 [ [[TMP9]], [[LOOP2_BODY_GUARD]] ], [ [[TMP11]], [[LOOP2_BODY]] ]
; CHECK-NEXT:    [[GUARD_VAR2]] = phi i32 [ [[GUARD_VAR1]], [[LOOP2_BODY_GUARD]] ], [ [[TMP11]], [[LOOP2_BODY]] ]
; CHECK-NEXT:    [[PREV_GUARD3:%.*]] = icmp eq i32 [[GUARD_VAR2]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD3]], label [[B5_GUARD]], label [[B3_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[GUARD_VAR6]] = phi i32 [ [[GUARD_VAR4]], [[B3_GUARD]] ], [ [[TMP4]], [[B3]] ]
; CHECK-NEXT:    [[PREV_GUARD7:%.*]] = icmp eq i32 [[GUARD_VAR6]], 8
; CHECK-NEXT:    br i1 [[PREV_GUARD7]], label [[B6]], label [[INNER_LOOP_GUARD]]
; CHECK:       b6:
; CHECK-NEXT:    store volatile i32 6, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %b1

b1:
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b3, label %b5

b3:
  store volatile i32 3, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %inner.loop, label %b6

inner.loop:
  %inner.cond = load i1, i1 addrspace(1)* null
  br i1 %inner.cond, label %inner.loop, label %b4

b4:
  store volatile i32 4, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  store volatile i32 5, i32 addrspace(1)* null
  %cond2 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond2, label %loop2.body, label %b6

loop2.body:
  %cond3 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond3, label %b5, label %b6

b6:
  store volatile i32 6, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}

define void @figure5b_phis(i32 %n) {
; CHECK-LABEL: @figure5b_phis(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ENTRY_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_PHI:%.*]] = phi i32 [ [[ENTRY_LOAD]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    store volatile i32 [[B1_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC10:%.*]] = phi i32 [ undef, [[B1]] ], [ [[I_INC11:%.*]], [[B4_SPLIT:%.*]] ]
; CHECK-NEXT:    [[B4_LOAD8:%.*]] = phi i32 [ undef, [[B1]] ], [ [[B4_LOAD9:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[B6_PHI_PH6:%.*]] = phi i32 [ undef, [[B1]] ], [ [[B6_PHI_PH7:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[B1]] ], [ [[I_INC11]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[B2_PHI:%.*]] = phi i32 [ [[B1_LOAD]], [[B1]] ], [ [[B4_LOAD9]], [[B4_SPLIT]] ]
; CHECK-NEXT:    store volatile i32 [[B2_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B2_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N:%.*]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[CMP]], i32 5, i32 3
; CHECK-NEXT:    br i1 [[CMP]], label [[B5_GUARD:%.*]], label [[B3_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD:%.*]] = icmp eq i32 [[TMP0]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD]], label [[B3:%.*]], label [[B4_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    [[B3_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B3_GUARD]] ]
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[B3_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND1]], i32 4, i32 6
; CHECK-NEXT:    br label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[B6_PHI_PH7]] = phi i32 [ [[B6_PHI_PH6]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[GUARD_VAR:%.*]] = phi i32 [ [[TMP0]], [[B3_GUARD]] ], [ [[TMP1]], [[B3]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR]], 4
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    [[B4_PHI:%.*]] = phi i32 [ [[B6_PHI_PH7]], [[B4_GUARD]] ]
; CHECK-NEXT:    [[B4_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B4_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC11]] = phi i32 [ [[I_INC10]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[B4_LOAD9]] = phi i32 [ [[B4_LOAD8]], [[B4_GUARD]] ], [ [[B4_LOAD]], [[B4]] ]
; CHECK-NEXT:    [[GUARD_VAR1:%.*]] = phi i32 [ [[GUARD_VAR]], [[B4_GUARD]] ], [ 4, [[B4]] ]
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[GUARD_VAR1]], 2
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B2]], label [[B5_GUARD]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[B6_PHI_PH5:%.*]] = phi i32 [ [[B6_PHI_PH7]], [[B4_SPLIT]] ], [ [[B6_PHI_PH6]], [[B2]] ]
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[GUARD_VAR1]], [[B4_SPLIT]] ], [ [[TMP0]], [[B2]] ]
; CHECK-NEXT:    [[PREV_GUARD4:%.*]] = icmp eq i32 [[GUARD_VAR3]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD4]], label [[B5:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    [[B5_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[B5_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B5_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[B6_PHI_PH:%.*]] = phi i32 [ [[B5_LOAD]], [[B5]] ], [ [[B6_PHI_PH5]], [[B5_GUARD]] ]
; CHECK-NEXT:    br label [[B6:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    [[B6_PHI:%.*]] = phi i32 [ [[B6_PHI_PH]], [[B6_GUARD]] ]
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %entry.load = load volatile i32, i32 addrspace(1)* null
  br label %b1

b1:
  %b1.phi = phi i32 [ %entry.load, %entry ]
  store volatile i32 %b1.phi, i32 addrspace(1)* null
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %b2.phi = phi i32 [ %b1.load, %b1 ], [ %b4.load, %b4 ]
  store volatile i32 %b2.phi, i32 addrspace(1)* null
  %b2.load = load volatile i32, i32 addrspace(1)* null
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b5, label %b3

b3:
  %b3.phi = phi i32 [ %b2.load, %b2 ]
  store volatile i32 3, i32 addrspace(1)* null
  %b3.load = load volatile i32, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  %b4.phi = phi i32 [ %b3.load, %b3 ]
  %b4.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b4.phi, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  %b5.phi = phi i32 [ %b2.load, %b2 ]
  %b5.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b5.phi, i32 addrspace(1)* null
  br label %b6

b6:
  %b6.phi = phi i32 [ %b3.load, %b3 ], [ %b5.load, %b5 ]
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}









; swap order of branch in b2
define void @figure5b_phis_swap_br2(i32 %n) {
; CHECK-LABEL: @figure5b_phis_swap_br2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ENTRY_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_PHI:%.*]] = phi i32 [ [[ENTRY_LOAD]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    store volatile i32 [[B1_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[B3_LOAD7:%.*]] = phi i32 [ undef, [[B1]] ], [ [[B3_LOAD8:%.*]], [[B4_SPLIT:%.*]] ]
; CHECK-NEXT:    [[B6_PHI5:%.*]] = phi i32 [ undef, [[B1]] ], [ [[B3_LOAD8]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[B1]] ], [ [[I_INC:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[B2_PHI:%.*]] = phi i32 [ [[B1_LOAD]], [[B1]] ], [ [[B4_LOAD:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    store volatile i32 [[B2_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B2_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N:%.*]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[CMP]], i32 3, i32 5
; CHECK-NEXT:    br label [[B5_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[GUARD_VAR:%.*]] = phi i32 [ 6, [[B5:%.*]] ], [ [[TMP0]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[PREV_GUARD1:%.*]] = icmp eq i32 [[GUARD_VAR]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD1]], label [[B3:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    [[B3_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B3_GUARD:%.*]] ]
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[B3_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND1]], i32 4, i32 6
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[LAST:%.*]] = icmp eq i32 [[GUARD_VAR2:%.*]], 4
; CHECK-NEXT:    br i1 [[LAST]], label [[B4:%.*]], label [[B6:%.*]]
; CHECK:       b4:
; CHECK-NEXT:    [[B4_PHI:%.*]] = phi i32 [ [[B3_LOAD8]], [[B4_GUARD:%.*]] ]
; CHECK-NEXT:    [[B4_LOAD]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B4_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC]] = add nsw i32 [[I]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    br label [[B2]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[PREV_GUARD:%.*]] = icmp eq i32 [[TMP0]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD]], label [[B5]], label [[B3_GUARD]]
; CHECK:       b5:
; CHECK-NEXT:    [[B5_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[B5_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B5_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B3_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[B3_LOAD8]] = phi i32 [ [[B3_LOAD7]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[GUARD_VAR2]] = phi i32 [ [[GUARD_VAR]], [[B3_GUARD]] ], [ [[TMP1]], [[B3]] ]
; CHECK-NEXT:    [[PREV_GUARD3:%.*]] = icmp eq i32 [[GUARD_VAR2]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD3]], label [[B6]], label [[B4_GUARD]]
; CHECK:       b6:
; CHECK-NEXT:    [[B6_PHI:%.*]] = phi i32 [ [[B3_LOAD8]], [[B6_GUARD]] ], [ [[B3_LOAD8]], [[B4_GUARD]] ]
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %entry.load = load volatile i32, i32 addrspace(1)* null
  br label %b1

b1:
  %b1.phi = phi i32 [ %entry.load, %entry ]
  store volatile i32 %b1.phi, i32 addrspace(1)* null
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %b2.phi = phi i32 [ %b1.load, %b1 ], [ %b4.load, %b4 ]
  store volatile i32 %b2.phi, i32 addrspace(1)* null
  %b2.load = load volatile i32, i32 addrspace(1)* null
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b3, label %b5

b3:
  %b3.phi = phi i32 [ %b2.load, %b2 ]
  store volatile i32 3, i32 addrspace(1)* null
  %b3.load = load volatile i32, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  %b4.phi = phi i32 [ %b3.load, %b3 ]
  %b4.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b4.phi, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  %b5.phi = phi i32 [ %b2.load, %b2 ]
  %b5.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b5.phi, i32 addrspace(1)* null
  br label %b6

b6:
  %b6.phi = phi i32 [ %b3.load, %b3 ], [ %b5.load, %b5 ]
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  br label %exit

exit:
  ret void
}

; structured condition skips over unstructured region.
define void @guarded_figure5b_phis(i1 %cond0, i32 %n) {
; CHECK-LABEL: @guarded_figure5b_phis(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ENTRY_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 100, i32 addrspace(1)* null
; CHECK-NEXT:    br i1 [[COND0:%.*]], label [[B0:%.*]], label [[EXIT:%.*]]
; CHECK:       b0:
; CHECK-NEXT:    [[B0_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_PHI:%.*]] = phi i32 [ [[B0_LOAD]], [[B0]] ]
; CHECK-NEXT:    store volatile i32 [[B1_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC10:%.*]] = phi i32 [ undef, [[B1]] ], [ [[I_INC11:%.*]], [[B4_SPLIT:%.*]] ]
; CHECK-NEXT:    [[B4_LOAD8:%.*]] = phi i32 [ undef, [[B1]] ], [ [[B4_LOAD9:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[B6_PHI_PH6:%.*]] = phi i32 [ undef, [[B1]] ], [ [[B6_PHI_PH7:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[B1]] ], [ [[I_INC11]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[B2_PHI:%.*]] = phi i32 [ [[B1_LOAD]], [[B1]] ], [ [[B4_LOAD9]], [[B4_SPLIT]] ]
; CHECK-NEXT:    store volatile i32 [[B2_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B2_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N:%.*]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[CMP]], i32 6, i32 4
; CHECK-NEXT:    br i1 [[CMP]], label [[B5_GUARD:%.*]], label [[B3_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD:%.*]] = icmp eq i32 [[TMP0]], 4
; CHECK-NEXT:    br i1 [[PREV_GUARD]], label [[B3:%.*]], label [[B4_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    [[B3_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B3_GUARD]] ]
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[B3_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND1]], i32 5, i32 7
; CHECK-NEXT:    br label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[B6_PHI_PH7]] = phi i32 [ [[B6_PHI_PH6]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[GUARD_VAR:%.*]] = phi i32 [ [[TMP0]], [[B3_GUARD]] ], [ [[TMP1]], [[B3]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR]], 5
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    [[B4_PHI:%.*]] = phi i32 [ [[B6_PHI_PH7]], [[B4_GUARD]] ]
; CHECK-NEXT:    [[B4_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B4_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC11]] = phi i32 [ [[I_INC10]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[B4_LOAD9]] = phi i32 [ [[B4_LOAD8]], [[B4_GUARD]] ], [ [[B4_LOAD]], [[B4]] ]
; CHECK-NEXT:    [[GUARD_VAR1:%.*]] = phi i32 [ [[GUARD_VAR]], [[B4_GUARD]] ], [ 5, [[B4]] ]
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[GUARD_VAR1]], 3
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B2]], label [[B5_GUARD]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[B6_PHI_PH5:%.*]] = phi i32 [ [[B6_PHI_PH7]], [[B4_SPLIT]] ], [ [[B6_PHI_PH6]], [[B2]] ]
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[GUARD_VAR1]], [[B4_SPLIT]] ], [ [[TMP0]], [[B2]] ]
; CHECK-NEXT:    [[PREV_GUARD4:%.*]] = icmp eq i32 [[GUARD_VAR3]], 6
; CHECK-NEXT:    br i1 [[PREV_GUARD4]], label [[B5:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    [[B5_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[B5_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B5_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[B6_PHI_PH:%.*]] = phi i32 [ [[B5_LOAD]], [[B5]] ], [ [[B6_PHI_PH5]], [[B5_GUARD]] ]
; CHECK-NEXT:    br label [[B6:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    [[B6_PHI:%.*]] = phi i32 [ [[B6_PHI_PH]], [[B6_GUARD]] ]
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    [[EXIT_PHI:%.*]] = phi i32 [ [[B6_PHI]], [[B6]] ], [ [[ENTRY_LOAD]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    store volatile i32 [[EXIT_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    ret void
;
entry:
  %entry.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 100, i32 addrspace(1)* null
  br i1 %cond0, label %b0, label %exit

b0:
  %b0.load = load volatile i32, i32 addrspace(1)* null
  br label %b1

b1:
  %b1.phi = phi i32 [ %b0.load, %b0 ]
  store volatile i32 %b1.phi, i32 addrspace(1)* null
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %b2.phi = phi i32 [ %b1.load, %b1 ], [ %b4.load, %b4 ]
  store volatile i32 %b2.phi, i32 addrspace(1)* null
  %b2.load = load volatile i32, i32 addrspace(1)* null
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b5, label %b3

b3:
  %b3.phi = phi i32 [ %b2.load, %b2 ]
  store volatile i32 3, i32 addrspace(1)* null
  %b3.load = load volatile i32, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  %b4.phi = phi i32 [ %b3.load, %b3 ]
  %b4.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b4.phi, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  %b5.phi = phi i32 [ %b2.load, %b2 ]
  %b5.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b5.phi, i32 addrspace(1)* null
  br label %b6

b6:
  %b6.phi = phi i32 [ %b3.load, %b3 ], [ %b5.load, %b5 ]
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  br label %exit

exit:
  %exit.phi = phi i32 [ %b6.phi, %b6 ], [ %entry.load, %entry ]
  store volatile i32 %exit.phi, i32 addrspace(1)* null
  ret void
}

; The block before the unstructured region has 2 predecessors
define void @multiple_entry_unstructured_region_figure5b_phis(i1 %cond0, i32 %n) {
; CHECK-LABEL: @multiple_entry_unstructured_region_figure5b_phis(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ENTRY_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 100, i32 addrspace(1)* null
; CHECK-NEXT:    br i1 [[COND0:%.*]], label [[PRE_0:%.*]], label [[PRE_1:%.*]]
; CHECK:       pre.0:
; CHECK-NEXT:    [[PRE_0_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 123, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1:%.*]]
; CHECK:       pre.1:
; CHECK-NEXT:    [[PRE_1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 123, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B1]]
; CHECK:       b1:
; CHECK-NEXT:    [[B1_PHI:%.*]] = phi i32 [ [[PRE_0_LOAD]], [[PRE_0]] ], [ [[PRE_1_LOAD]], [[PRE_1]] ]
; CHECK-NEXT:    store volatile i32 [[B1_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B1_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B2:%.*]]
; CHECK:       b2:
; CHECK-NEXT:    [[I_INC10:%.*]] = phi i32 [ undef, [[B1]] ], [ [[I_INC11:%.*]], [[B4_SPLIT:%.*]] ]
; CHECK-NEXT:    [[B4_LOAD8:%.*]] = phi i32 [ undef, [[B1]] ], [ [[B4_LOAD9:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[B6_PHI_PH6:%.*]] = phi i32 [ undef, [[B1]] ], [ [[B6_PHI_PH7:%.*]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[I:%.*]] = phi i32 [ 0, [[B1]] ], [ [[I_INC11]], [[B4_SPLIT]] ]
; CHECK-NEXT:    [[B2_PHI:%.*]] = phi i32 [ [[B1_LOAD]], [[B1]] ], [ [[B4_LOAD9]], [[B4_SPLIT]] ]
; CHECK-NEXT:    store volatile i32 [[B2_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[B2_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I]], [[N:%.*]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[CMP]], i32 7, i32 5
; CHECK-NEXT:    br i1 [[CMP]], label [[B5_GUARD:%.*]], label [[B3_GUARD:%.*]]
; CHECK:       b3.guard:
; CHECK-NEXT:    [[PREV_GUARD:%.*]] = icmp eq i32 [[TMP0]], 5
; CHECK-NEXT:    br i1 [[PREV_GUARD]], label [[B3:%.*]], label [[B4_GUARD:%.*]]
; CHECK:       b3:
; CHECK-NEXT:    [[B3_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B3_GUARD]] ]
; CHECK-NEXT:    store volatile i32 3, i32 addrspace(1)* null
; CHECK-NEXT:    [[B3_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    [[COND1:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[COND1]], i32 6, i32 8
; CHECK-NEXT:    br label [[B4_GUARD]]
; CHECK:       b4.guard:
; CHECK-NEXT:    [[B6_PHI_PH7]] = phi i32 [ [[B6_PHI_PH6]], [[B3_GUARD]] ], [ [[B3_LOAD]], [[B3]] ]
; CHECK-NEXT:    [[GUARD_VAR:%.*]] = phi i32 [ [[TMP0]], [[B3_GUARD]] ], [ [[TMP1]], [[B3]] ]
; CHECK-NEXT:    [[BE_GUARD:%.*]] = icmp eq i32 [[GUARD_VAR]], 6
; CHECK-NEXT:    br i1 [[BE_GUARD]], label [[B4:%.*]], label [[B4_SPLIT]]
; CHECK:       b4:
; CHECK-NEXT:    [[B4_PHI:%.*]] = phi i32 [ [[B6_PHI_PH7]], [[B4_GUARD]] ]
; CHECK-NEXT:    [[B4_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B4_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    [[I_INC:%.*]] = add nsw i32 [[I]], 1
; CHECK-NEXT:    br label [[B4_SPLIT]]
; CHECK:       b4.split:
; CHECK-NEXT:    [[I_INC11]] = phi i32 [ [[I_INC10]], [[B4_GUARD]] ], [ [[I_INC]], [[B4]] ]
; CHECK-NEXT:    [[B4_LOAD9]] = phi i32 [ [[B4_LOAD8]], [[B4_GUARD]] ], [ [[B4_LOAD]], [[B4]] ]
; CHECK-NEXT:    [[GUARD_VAR1:%.*]] = phi i32 [ [[GUARD_VAR]], [[B4_GUARD]] ], [ 6, [[B4]] ]
; CHECK-NEXT:    [[PREV_GUARD2:%.*]] = icmp eq i32 [[GUARD_VAR1]], 4
; CHECK-NEXT:    br i1 [[PREV_GUARD2]], label [[B2]], label [[B5_GUARD]]
; CHECK:       b5.guard:
; CHECK-NEXT:    [[B6_PHI_PH5:%.*]] = phi i32 [ [[B6_PHI_PH7]], [[B4_SPLIT]] ], [ [[B6_PHI_PH6]], [[B2]] ]
; CHECK-NEXT:    [[GUARD_VAR3:%.*]] = phi i32 [ [[GUARD_VAR1]], [[B4_SPLIT]] ], [ [[TMP0]], [[B2]] ]
; CHECK-NEXT:    [[PREV_GUARD4:%.*]] = icmp eq i32 [[GUARD_VAR3]], 7
; CHECK-NEXT:    br i1 [[PREV_GUARD4]], label [[B5:%.*]], label [[B6_GUARD:%.*]]
; CHECK:       b5:
; CHECK-NEXT:    [[B5_PHI:%.*]] = phi i32 [ [[B2_LOAD]], [[B5_GUARD]] ]
; CHECK-NEXT:    [[B5_LOAD:%.*]] = load volatile i32, i32 addrspace(1)* null
; CHECK-NEXT:    store volatile i32 [[B5_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[B6_GUARD]]
; CHECK:       b6.guard:
; CHECK-NEXT:    [[B6_PHI_PH:%.*]] = phi i32 [ [[B5_LOAD]], [[B5]] ], [ [[B6_PHI_PH5]], [[B5_GUARD]] ]
; CHECK-NEXT:    br label [[B6:%.*]]
; CHECK:       b6:
; CHECK-NEXT:    [[B6_PHI:%.*]] = phi i32 [ [[B6_PHI_PH]], [[B6_GUARD]] ]
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    store volatile i32 [[B6_PHI]], i32 addrspace(1)* null
; CHECK-NEXT:    ret void
;
entry:
  %entry.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 100, i32 addrspace(1)* null
  br i1 %cond0, label %pre.0, label %pre.1

pre.0:
  %pre.0.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 123, i32 addrspace(1)* null
  br label %b1

pre.1:
  %pre.1.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 123, i32 addrspace(1)* null
  br label %b1

b1:
  %b1.phi = phi i32 [ %pre.0.load, %pre.0 ], [ %pre.1.load, %pre.1 ]
  store volatile i32 %b1.phi, i32 addrspace(1)* null
  %b1.load = load volatile i32, i32 addrspace(1)* null
  br label %b2

b2:
  %i = phi i32 [ 0, %b1 ], [ %i.inc, %b4 ]
  %b2.phi = phi i32 [ %b1.load, %b1 ], [ %b4.load, %b4 ]
  store volatile i32 %b2.phi, i32 addrspace(1)* null
  %b2.load = load volatile i32, i32 addrspace(1)* null
  %cmp = icmp slt i32 %i, %n
  br i1 %cmp, label %b5, label %b3

b3:
  %b3.phi = phi i32 [ %b2.load, %b2 ]
  store volatile i32 3, i32 addrspace(1)* null
  %b3.load = load volatile i32, i32 addrspace(1)* null
  %cond1 = load volatile i1, i1 addrspace(1)* null
  br i1 %cond1, label %b4, label %b6

b4:
  %b4.phi = phi i32 [ %b3.load, %b3 ]
  %b4.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b4.phi, i32 addrspace(1)* null
  %i.inc = add nsw i32 %i, 1
  br label %b2

b5:
  %b5.phi = phi i32 [ %b2.load, %b2 ]
  %b5.load = load volatile i32, i32 addrspace(1)* null
  store volatile i32 %b5.phi, i32 addrspace(1)* null
  br label %b6

b6:
  %b6.phi = phi i32 [ %b3.load, %b3 ], [ %b5.load, %b5 ]
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  br label %exit

exit:
  store volatile i32 %b6.phi, i32 addrspace(1)* null
  ret void
}
