; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -linearize-cfg %s | FileCheck %s

define void @scc_vs_loop() {
; CHECK-LABEL: @scc_vs_loop(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    store volatile i32 0, i32 addrspace(1)* undef
; CHECK-NEXT:    [[C:%.*]] = load volatile i1, i1 addrspace(1)* undef
; CHECK-NEXT:    br i1 [[C]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    store volatile i32 0, i32 addrspace(1)* undef
; CHECK-NEXT:    br label [[LEFT]]
; CHECK:       right:
; CHECK-NEXT:    store volatile i32 1, i32 addrspace(1)* undef
; CHECK-NEXT:    br label [[LEFT]]
;
entry:
  br label %loop

loop:
  store volatile i32 0, i32 addrspace(1)* undef
  %c = load volatile i1, i1 addrspace(1)* undef
  br i1 %c, label %left, label %right

left:
  store volatile i32 0, i32 addrspace(1)* undef
  br label %left

right:
  store volatile i32 1, i32 addrspace(1)* undef
  br label %left
}
