; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -linearize-cfg %s | FileCheck %s

define void @two_loops_one_header() {
; CHECK-LABEL: @two_loops_one_header(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    store volatile i32 0, i32 addrspace(1)* null
; CHECK-NEXT:    [[C:%.*]] = load volatile i1, i1 addrspace(1)* null
; CHECK-NEXT:    br i1 [[C]], label [[LEFT:%.*]], label [[RIGHT:%.*]]
; CHECK:       left:
; CHECK-NEXT:    store volatile i32 0, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[LOOP]]
; CHECK:       right:
; CHECK-NEXT:    store volatile i32 1, i32 addrspace(1)* null
; CHECK-NEXT:    br label [[LOOP]]
;
entry:
  br label %loop

loop:
  store volatile i32 0, i32 addrspace(1)* null
  %c = load volatile i1, i1 addrspace(1)* null
  br i1 %c, label %left, label %right

left:
  store volatile i32 0, i32 addrspace(1)* null
  br label %loop

right:
  store volatile i32 1, i32 addrspace(1)* null
  br label %loop
}
